
language: elixir

elixir:
  - 1.5.3
  - 1.6.0
otp_release:
  - 18.3
  - 19.3
  - 20.2

matrix:
  exclude:
    - elixir: 1.6.0
      otp_release: 18.3

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

scripts:
  - mix compile

